from flask import (
    Blueprint,
    send_file
)

from flask_login import (
    login_required,
    current_user
)

from database.models import (
    SentimentResult,
    Report
)
from flask import render_template

import pandas as pd
from io import BytesIO
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

from reportlab.lib import colors

from utils.audit import create_log
reports_bp = Blueprint(
    "reports",
    __name__
)
@reports_bp.route("/export/csv")
@login_required
def export_csv():

    results = SentimentResult.query.filter_by(
        user_id=current_user.id
    ).all()

    data = []

    for row in results:

        data.append({
            "Date": row.prediction_date,
            "Sentiment": row.sentiment,
            "Confidence": row.confidence_score,
            "Review": row.text
        })

    df = pd.DataFrame(data)

    output = BytesIO()

    df.to_csv(
        output,
        index=False
    )

    output.seek(0)
    create_log(
        current_user.id,
        "CSV Report Generated"
    )
    from utils.notification import create_notification
    create_notification(
        current_user.id,
        "Report Generated",
        "Your CSV report is ready for download."
    )
    report = Report(
        report_name="Sentiment Report",
        report_type="CSV",
        generated_by=current_user.id
    )
    db.session.add(report)
    db.session.commit()
    return send_file(
        output,
        mimetype="text/csv",
        as_attachment=True,
        download_name="sentiment_report.csv"
    )
@reports_bp.route("/export/excel")
@login_required
def export_excel():

    results = SentimentResult.query.filter_by(
        user_id=current_user.id
    ).all()

    data = []

    for row in results:

        data.append({
            "Date": row.prediction_date,
            "Sentiment": row.sentiment,
            "Confidence": row.confidence_score,
            "Review": row.text
        })

    df = pd.DataFrame(data)

    output = BytesIO()

    with pd.ExcelWriter(
        output,
        engine="openpyxl"
    ) as writer:

        df.to_excel(
            writer,
            index=False
        )

    output.seek(0)
    create_log(
            current_user.id,
            "Excel Report Generated"
        )
    from utils.notification import create_notification
    create_notification(
        current_user.id,
        "Report Generated",
        "Your Excel report is ready for download."
    )
    report = Report(
        report_name="Sentiment Report",
        report_type="Excel",
        generated_by=current_user.id
    )
    db.session.add(report)
    db.session.commit()
    return send_file(
        output,
        mimetype=
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        as_attachment=True,
        download_name="sentiment_report.xlsx"
    )

@reports_bp.route("/export/pdf")
@login_required
def export_pdf():

    results = SentimentResult.query.filter_by(
        user_id=current_user.id
    ).all()

    output = BytesIO()

    doc = SimpleDocTemplate(output)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "Sentiment Analysis Report",
            styles["Title"]
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    elements.append(
        Paragraph(
            f"Generated By: {current_user.name}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"Email: {current_user.email}",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1, 12)
    )

    total = len(results)

    positive = len([
        r for r in results
        if r.sentiment == "Positive"
    ])

    negative = len([
        r for r in results
        if r.sentiment == "Negative"
    ])

    neutral = len([
        r for r in results
        if r.sentiment == "Neutral"
    ])

    elements.append(
        Paragraph(
            f"Total Reviews: {total}",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"Positive Reviews: {positive}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"Negative Reviews: {negative}",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"Neutral Reviews: {neutral}",
            styles["Normal"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            "Recent Analysis",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 10)
    )

    for row in results[-20:]:

        elements.append(
            Paragraph(
                f"<b>{row.sentiment}</b> "
                f"({row.confidence_score:.2f}%)",
                styles["Normal"]
            )
        )

        elements.append(
            Paragraph(
                row.text[:250],
                styles["BodyText"]
            )
        )

        elements.append(
            Spacer(1, 8)
        )

    doc.build(elements)

    output.seek(0)
    create_log(
        current_user.id,
        "PDF Report Generated"
    )
    from utils.notification import create_notification
    create_notification(
        current_user.id,
        "Report Generated",
        "Your PDF report is ready for download."
    )
    report = Report(
        report_name="Sentiment Report",
        report_type="PDF",
        generated_by=current_user.id
    )

    db.session.add(report)
    db.session.commit()
    return send_file(
        output,
        mimetype="application/pdf",
        as_attachment=True,
        download_name="sentiment_report.pdf"
    )


@reports_bp.route("/reports")
@login_required
def reports():

    return render_template(
        "reports.html"
    )